In [1]:
# and we will store the data in bigquery
import pandas_gbq
import pydata_google_auth

import yfinance as yf # for downloading stock data

### Authentication

In [2]:
# BigQuery authentication
SCOPES = [
    'https://www.googleapis.com/auth/cloud-platform',
    'https://www.googleapis.com/auth/drive',
]

credentials = pydata_google_auth.get_user_credentials(
    SCOPES,
    # Note, this doesn't work if you're running from a notebook on a
    # remote sever, such as over SSH or with Google Colab. In those cases,
    # install the gcloud command line interface and authenticate with the
    # `gcloud auth application-default login` command and the `--no-browser`
    # option.
    auth_local_webserver=True,
)

### Getting daily data from last month

In [9]:
dat = yf.Ticker("MSFT")
msft_df = dat.history(period='1mo')
msft_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-03-18 00:00:00-04:00,387.070007,387.369995,381.100006,383.519989,19486900,0.0,0.0
2025-03-19 00:00:00-04:00,385.529999,389.679993,384.000000,387.820007,19185500,0.0,0.0
2025-03-20 00:00:00-04:00,385.739990,391.790009,383.279999,386.839996,18470500,0.0,0.0
2025-03-21 00:00:00-04:00,383.220001,391.739990,382.799988,391.260010,39675900,0.0,0.0
2025-03-24 00:00:00-04:00,395.399994,395.399994,389.809998,393.079987,21004500,0.0,0.0
2025-03-25 00:00:00-04:00,393.920013,396.359985,392.640015,395.160004,15775000,0.0,0.0
2025-03-26 00:00:00-04:00,395.000000,395.309998,388.570007,389.970001,16108400,0.0,0.0
2025-03-27 00:00:00-04:00,390.130005,392.239990,387.399994,390.579987,13766800,0.0,0.0
2025-03-28 00:00:00-04:00,388.079987,389.130005,376.929993,378.799988,21632000,0.0,0.0
2025-03-31 00:00:00-04:00,372.540009,377.070007,367.239990,375.390015,35184700,0.0,0.0
2025-04-01 00:00:00-04:00,374.649994,382.850006,373.230011,382.190002,19689500,0.0,0.0
2025-04-02 00:00:00-04:00,377.970001,385.079987,376.619995,382.140015,16092600,0.0,0.0
2025-04-03 00:00:00-04:00,374.790009,377.480011,369.350006,373.109985,30198000,0.0,0.0
2025-04-04 00:00:00-04:00,364.130005,374.589996,359.480011,359.839996,49209900,0.0,0.0
2025-04-07 00:00:00-04:00,350.880005,371.000000,344.790009,357.859985,50425000,0.0,0.0
2025-04-08 00:00:00-04:00,368.260010,373.649994,350.250000,354.559998,35868900,0.0,0.0
2025-04-09 00:00:00-04:00,353.540009,393.230011,353.100006,390.489990,50199700,0.0,0.0
2025-04-10 00:00:00-04:00,382.059998,383.899994,367.799988,381.350006,38024400,0.0,0.0
2025-04-11 00:00:00-04:00,380.640015,390.049988,378.890015,388.450012,23839200,0.0,0.0
2025-04-14 00:00:00-04:00,393.220001,394.649994,384.209991,387.809998,19251200,0.0,0.0
2025-04-15 00:00:00-04:00,388.510010,391.890015,384.160004,385.730011,17199900,0.0,0.0
2025-04-16 00:00:00-04:00,380.670013,381.609985,368.000000,371.609985,21967800,0.0,0.0
2025-04-17 00:00:00-04:00,373.440002,374.321503,366.890015,367.779999,20858907,0.0,0.0

## Creating BigQuery Table

In [10]:
# to BigQuery
pandas_gbq.to_gbq(
    msft_df,
    destination_table='stock_data.msft',
    project_id='sipa-adv-c-roberto',
    if_exists='replace',
    credentials=credentials,
)

100%|██████████| 1/1 [00:00<00:00, 874.00it/s]

In [12]:
import json

In [13]:
bq_credentials = """
{
  "type": "service_account",
  "project_id": "sipa-adv-c-roberto",
  "private_key_id": "876ad52d3ab1986becae68062b203d4546bd85ef",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDD4LnzefsyaYQK\nmrEUxc7nwSywziFYaJCikTWnpMwGq63nJm0VlFOAHTQ+Bms1ctgN9sr3zR9T/1bY\nbw6Cds4oAsTkZXDYippi8uRUvpLZtuQjUejEZISRXFZ3Yeeqq6hZrSrYR9f27IV0\niBLRmiIICrsMh0N4LWnYuRU+IDJEfgovGw1B86YdYqN8wBFh/T+ewFnjEetv98Pr\nojmRBas1/L4TI31C1shcbjTCcxxgfM/tURoDSRGQtlZVg+BLwsD+jO6/8I27B1+d\nVDMcHKPfDbRxzJgKgGDRl6c1PbfEvF9Hx3P8dkz0UFbxN29mY+ZIEogdkbkqPn6W\nTvd+ug/tAgMBAAECggEAHbo8Nm+3mCvL4pkeEW9A6srWR8IM7QA3nTiJCleYMFX7\nV1atXQZNEuc7v8MVH8A9eocPQEL1A3g/26qlKtcxjAB5lckwcmi8rBI9ZYAjxN99\nKcAbYbz4op//LnChKnWRYATIORlUNTEpwukI5B8ulYZdY3Ye3v0TcJUMXIih4GN1\nkvMCHzaK3EBo6xXQMs9jY/UQm67OD7eDA9o333bqTevlz0VNhi/zUhsB5DsofhrI\naYOTcrmWrzk6l/J8q5AOiXxHbFnxyvvVMu1SAqG1jfTILGl2U0aNOZ1hISqwn7Fd\ngZ1yeU0Lt/+7tnX3oqu/888Z1hAtA2KTRObR5X260QKBgQDm7zREm9BVuLOC1AFx\nawvRfyymzvNDvzB2pOKNlwvhDXoIMzgFLOLNlewquD0jN+ucHt+PBnJMKdbhttOs\nfBMMeJyH2UoZpw0XcbYNiTbzK7EScvsjHQ7L6gwQqiPry3K6DN58rVvvC1M2uMpB\nWxbIWMyHFvkkTf+zDnPxLMOk/QKBgQDZI27KMAU8pPi1iUr3/9vz6ky7FVGd+u3G\nU8keTtPgacpq/1zbsyg1e69BUDLT0x2Aa/z84OYm74oN0qU/aVuTqsgkol6qXK9s\ndhC/lJcegKlZWbC7E+MWdehk7NIvarkoehRdc6ANIRFCuwSpED1RHSTtLwfYrED9\n4B932BABsQKBgFBUkvzuqmi3KBJxRtM6JlFIiLK5uFsvjV8n+frAuQwfEPz7PBho\nxbg314AAuJugnx+eiauJ1YZy42F+pGESg9nJtsF2r1T/DAnEr0xEF848u4qsXnmX\naQc7sdi2JmqmSZE4WshJ0Xn0mYymeQyE8AbfBL5VGnMrgq+5blFNffzNAoGAXqsp\nGXO4RMl0Ocmi6t8daYnEbGiODf+h/S74Z4NcsuHMw7uUI6FHrZHARgyOLHZFzYDH\nawUustkK6p3lN/FaYNY7rmUwOrxwKyyKfsxs2nqj2vXUrKut/VPov1/U/6FbGr+m\n81t+81pwaRSaoo8W/K9lMxenJxtqtoUpkxmbWPECgYEA1rBy0zX5QZ/7xN7+pQ5Y\nxwqHNMdQQ8WNEjgMLvA/vegWHlfVinsnvDYjRXtzTPjkYV+JEQ1JisII0G8PGA8T\nkPQIl4jk35lTL3HAVaN3z5lrx9ccKqdlSa5T1+yKdXQiKJJ5ekaN2+k09ftpvvYO\nzP3Bb7GfKNfgkl51Vdok1bE=\n-----END PRIVATE KEY-----\n",
  "client_email": "lab13-example@sipa-adv-c-roberto.iam.gserviceaccount.com",
  "client_id": "115701079677709179069",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lab13-example%40sipa-adv-c-roberto.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
bq_credentials = json.loads(bq_credentials)

JSONDecodeError: Invalid control character at: line 6 column 46 (char 179)